### ISSUE TITLE
Seekbar contrast in dark theme

### ISSUE THREAD

**Issue by peteruithoven** [elementary/granite#150]
One of my smaller annoyances with elementary Videos is how hard it is to see how far along a video is. This is mostly caused by the lack of contrast in the dark themes seekbar. 
For reference a screenshot of Videos in Loki:
![screenshot from 2018-02-10 10 22 43](https://user-images.githubusercontent.com/523210/36060604-6497092e-0e4d-11e8-8d67-a5581e1ec811.png)

A screenshot of the latest master branch of Videos on github:
![screenshot from 2018-02-10 10 25 04](https://user-images.githubusercontent.com/523210/36060607-6e560ee2-0e4d-11e8-83c8-0c2479d907b0.png)

The contrast in the light theme seekbar seems a lot better, for reference Videos in light theme:
![screenshot from 2018-02-10 10 34 18](https://user-images.githubusercontent.com/523210/36060651-fd725590-0e4d-11e8-9db5-7d91c1945095.png)

## Comparison 
The seekbar in Youtube:
![screenshot from 2018-02-10 11 31 23](https://user-images.githubusercontent.com/523210/36061153-868374d8-0e56-11e8-8408-f55d9eb6161a.png)

Videos in Arc-solid theme:
![screenshot from 2018-02-10 11 34 35](https://user-images.githubusercontent.com/523210/36061155-8ab8350c-0e56-11e8-8b0c-e556ab481637.png)

**Comment by peteruithoven** [comment]
Looking into this, I understand a [Gtk.Scale](https://valadoc.org/gtk+-3.0/Gtk.Scale.html) is used, which style is overriden in the elementary stylesheet. 
I think the colors are defined here:
https://github.com/elementary/stylesheet/blob/master/gtk-3.0/gtk-widgets-dark.css#L112-L193

Which might make this a elementary Stylesheet issue.

**Comment by peteruithoven** [comment]
Some experiments:

## White
![screenshot from 2018-02-10 14 29 16](https://user-images.githubusercontent.com/523210/36062562-70b232ca-0e6f-11e8-9532-12fe92e76aa6.png)

``` css
.scale.highlight.left {
    border-color: alpha (#000, 0.5);
    background-image:
        linear-gradient(
            to bottom,
            alpha (
                #fff,
                0.4
            ),
            alpha (
                #fff,
                0.3
            )
        );
}
```

## Blue
![screenshot from 2018-02-10 14 33 16](https://user-images.githubusercontent.com/523210/36062561-67fa1652-0e6f-11e8-84fa-07cdfc7bd1a4.png)

``` css
.scale.highlight.left {
    border-color: alpha (#002e99, 0.5);
    background-image:
        linear-gradient(
            to bottom,
            alpha (
		#3689e6,
                0.8
            ),
            alpha (
                #3689e6,
                0.7
            )
        );
}
```
